spring.application.name=core-banking-system

spring.datasource.url=jdbc:postgresql://localhost:5434/core_banking?timezone=UTC
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.properties.hibernate.jdbc.time_zone=UTC